import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const sharp=require('C:/Users/desig/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const original=path.resolve('Redesign/originals/ui'),target=path.resolve(process.argv[2]||'Redesign/ready');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const all=await fs.readdir(original),names=all.filter(x=>x.endsWith('.png')).sort(),rows=[];
for(const file of names){const oldBytes=await fs.readFile(path.join(original,file)),newBytes=await fs.readFile(path.join(target,file)),old=await sharp(oldBytes).metadata(),now=await sharp(newBytes).metadata();const stats=await sharp(newBytes).stats();if(old.width!==now.width||old.height!==now.height)throw Error(`Size mismatch: ${file}`);if(sha(oldBytes)===sha(newBytes))throw Error(`Unchanged image: ${file}`);if(now.format!=='png')throw Error(`Invalid format: ${file}`);if(!/^bg[12]\.png$/.test(file)&&(!now.hasAlpha||stats.isOpaque))throw Error(`Missing transparency: ${file}`);rows.push({file,width:now.width,height:now.height,alpha:now.hasAlpha,sha256:sha(newBytes),sizeMatches:true});}
let unchanged=0;for(const file of all.filter(x=>!x.endsWith('.png'))){const a=await fs.readFile(path.join(original,file)),b=await fs.readFile(path.join('Assets/Scenes/ui',file));if(sha(a)!==sha(b))throw Error(`Non-image file changed: ${file}`);unchanged++;}
const report={images:rows.length,allDimensionsMatch:true,allImagesReplaced:true,nonImageFilesUnchanged:unchanged,unityPlayModeTested:false,checkedFolder:target,assets:rows};await fs.writeFile('Redesign/validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify({images:rows.length,allDimensionsMatch:true,allImagesReplaced:true,nonImageFilesUnchanged:unchanged},null,2));
const cellW=260,cellH=205,cols=5,width=cellW*cols,height=Math.ceil(names.length/cols)*cellH+90,layers=[];
const header=`<svg width="${width}" height="90"><rect width="100%" height="100%" fill="#302641"/><text x="30" y="40" fill="#f9c5e6" font-size="27" font-family="Segoe UI" font-weight="bold">GACHA NOX · UI ASSET REDESIGN</text><text x="30" y="69" fill="#cfbbeb" font-size="16" font-family="Segoe UI">45 replacement PNGs · original dimensions · original Unity references</text></svg>`;layers.push({input:Buffer.from(header),left:0,top:0});
for(let i=0;i<names.length;i++){const x=(i%cols)*cellW,y=Math.floor(i/cols)*cellH+90,file=names[i],r=rows[i];const tile=`<svg width="${cellW}" height="${cellH}"><rect x="4" y="4" width="252" height="197" rx="12" fill="${i%2?'#eee6f6':'#e6e6f3'}"/><text x="12" y="177" fill="#403050" font-size="13" font-family="Segoe UI" font-weight="bold">${file}</text><text x="12" y="194" fill="#79628e" font-size="11" font-family="Segoe UI">${r.width} × ${r.height}</text></svg>`;layers.push({input:Buffer.from(tile),left:x,top:y});const resized=await sharp(path.join(target,file)).resize(236,154,{fit:'inside'}).png().toBuffer({resolveWithObject:true});layers.push({input:resized.data,left:x+Math.floor((cellW-resized.info.width)/2),top:y+10+Math.floor((154-resized.info.height)/2)});}
await sharp({create:{width,height,channels:4,background:'#d6cbe5'}}).composite(layers).png().toFile('Redesign/Gacha-Nox-UI-preview.png');
